[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
# Wähle gängige Regel-Sets; wir können später schärfer stellen.
select = ["E", "F", "W", "I"]
ignore = []
target-version = "py311"
