version: '3.9'

services:
  neo4j:
    image: neo4j:5.20
    container_name: neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/s3cr3tP@ss
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"   # HTTP UI
      - "7687:7687"   # Bolt driver
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:

